name: dissau_automatic
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  readsms: ^0.2.0+4
  permission_handler: ^11.3.1
  http: ^1.2.2
  flutter_background: ^1.3.0+1
  workmanager: ^0.5.2
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  flutter_riverpod: ^2.5.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  flutter_foreground_service: ^0.4.1
  flutter_background_service:
  flutter_local_notifications: ^17.2.4
  flutter_stripe: ^10.2.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#25253a"
  image: assets/images/splash_logo.png
  branding: assets/images/splash_logo.png
  color_dark: "#25253a"
  image_dark: assets/images/splash_logo.png
  branding_dark: assets/images/splash_logo.png

  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#25253a"
    image_dark: assets/images/splash_logo.png
    icon_background_color_dark: "#25253a"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/Baner.png
    - assets/images/icon_bot.png
    - assets/images/Bedge.png
    - assets/images/splash_logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
